apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: meilisearch
  name: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: meilisearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: meilisearch
    spec:
      containers:
        - env:
            - name: ALLOW_EMAIL_LOGIN
              valueFrom:
                configMapKeyRef:
                  key: ALLOW_EMAIL_LOGIN
                  name: env
            - name: ALLOW_REGISTRATION
              valueFrom:
                configMapKeyRef:
                  key: ALLOW_REGISTRATION
                  name: env
            - name: ALLOW_SOCIAL_LOGIN
              valueFrom:
                configMapKeyRef:
                  key: ALLOW_SOCIAL_LOGIN
                  name: env
            - name: ALLOW_SOCIAL_REGISTRATION
              valueFrom:
                configMapKeyRef:
                  key: ALLOW_SOCIAL_REGISTRATION
                  name: env
            - name: ANTHROPIC_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: ANTHROPIC_API_KEY
                  name: env
            - name: APP_TITLE
              valueFrom:
                configMapKeyRef:
                  key: APP_TITLE
                  name: env
            - name: ASSISTANTS_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: ASSISTANTS_API_KEY
                  name: env
            - name: AZURE_AI_SEARCH_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: AZURE_AI_SEARCH_API_KEY
                  name: env
            - name: AZURE_AI_SEARCH_API_VERSION
              valueFrom:
                configMapKeyRef:
                  key: AZURE_AI_SEARCH_API_VERSION
                  name: env
            - name: AZURE_AI_SEARCH_INDEX_NAME
              valueFrom:
                configMapKeyRef:
                  key: AZURE_AI_SEARCH_INDEX_NAME
                  name: env
            - name: AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE
              valueFrom:
                configMapKeyRef:
                  key: AZURE_AI_SEARCH_SEARCH_OPTION_QUERY_TYPE
                  name: env
            - name: AZURE_AI_SEARCH_SEARCH_OPTION_SELECT
              valueFrom:
                configMapKeyRef:
                  key: AZURE_AI_SEARCH_SEARCH_OPTION_SELECT
                  name: env
            - name: AZURE_AI_SEARCH_SEARCH_OPTION_TOP
              valueFrom:
                configMapKeyRef:
                  key: AZURE_AI_SEARCH_SEARCH_OPTION_TOP
                  name: env
            - name: AZURE_AI_SEARCH_SERVICE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: AZURE_AI_SEARCH_SERVICE_ENDPOINT
                  name: env
            - name: BAN_DURATION
              valueFrom:
                configMapKeyRef:
                  key: BAN_DURATION
                  name: env
            - name: BAN_INTERVAL
              valueFrom:
                configMapKeyRef:
                  key: BAN_INTERVAL
                  name: env
            - name: BAN_VIOLATIONS
              valueFrom:
                configMapKeyRef:
                  key: BAN_VIOLATIONS
                  name: env
            - name: BINGAI_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: BINGAI_TOKEN
                  name: env
            - name: CHECK_BALANCE
              valueFrom:
                configMapKeyRef:
                  key: CHECK_BALANCE
                  name: env
            - name: CONCURRENT_MESSAGE_MAX
              valueFrom:
                configMapKeyRef:
                  key: CONCURRENT_MESSAGE_MAX
                  name: env
            - name: CONCURRENT_VIOLATION_SCORE
              valueFrom:
                configMapKeyRef:
                  key: CONCURRENT_VIOLATION_SCORE
                  name: env
            - name: CONSOLE_JSON
              valueFrom:
                configMapKeyRef:
                  key: CONSOLE_JSON
                  name: env
            - name: CREDS_IV
              valueFrom:
                configMapKeyRef:
                  key: CREDS_IV
                  name: env
            - name: CREDS_KEY
              valueFrom:
                configMapKeyRef:
                  key: CREDS_KEY
                  name: env
            - name: DEBUG_CONSOLE
              valueFrom:
                configMapKeyRef:
                  key: DEBUG_CONSOLE
                  name: env
            - name: DEBUG_LOGGING
              valueFrom:
                configMapKeyRef:
                  key: DEBUG_LOGGING
                  name: env
            - name: DEBUG_OPENAI
              valueFrom:
                configMapKeyRef:
                  key: DEBUG_OPENAI
                  name: env
            - name: DEBUG_PLUGINS
              valueFrom:
                configMapKeyRef:
                  key: DEBUG_PLUGINS
                  name: env
            - name: DISCORD_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_CALLBACK_URL
                  name: env
            - name: DISCORD_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_CLIENT_ID
                  name: env
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_CLIENT_SECRET
                  name: env
            - name: DOMAIN_CLIENT
              valueFrom:
                configMapKeyRef:
                  key: DOMAIN_CLIENT
                  name: env
            - name: DOMAIN_SERVER
              valueFrom:
                configMapKeyRef:
                  key: DOMAIN_SERVER
                  name: env
            - name: EMAIL_ALLOW_SELFSIGNED
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_ALLOW_SELFSIGNED
                  name: env
            - name: EMAIL_ENCRYPTION
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_ENCRYPTION
                  name: env
            - name: EMAIL_ENCRYPTION_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_ENCRYPTION_HOSTNAME
                  name: env
            - name: EMAIL_FROM
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_FROM
                  name: env
            - name: EMAIL_FROM_NAME
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_FROM_NAME
                  name: env
            - name: EMAIL_HOST
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_HOST
                  name: env
            - name: EMAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_PASSWORD
                  name: env
            - name: EMAIL_PORT
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_PORT
                  name: env
            - name: EMAIL_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_SERVICE
                  name: env
            - name: EMAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: EMAIL_USERNAME
                  name: env
            - name: FACEBOOK_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  key: FACEBOOK_CALLBACK_URL
                  name: env
            - name: FACEBOOK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: FACEBOOK_CLIENT_ID
                  name: env
            - name: FACEBOOK_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: FACEBOOK_CLIENT_SECRET
                  name: env
            - name: FIREBASE_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: FIREBASE_API_KEY
                  name: env
            - name: FIREBASE_APP_ID
              valueFrom:
                configMapKeyRef:
                  key: FIREBASE_APP_ID
                  name: env
            - name: FIREBASE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: FIREBASE_AUTH_DOMAIN
                  name: env
            - name: FIREBASE_MESSAGING_SENDER_ID
              valueFrom:
                configMapKeyRef:
                  key: FIREBASE_MESSAGING_SENDER_ID
                  name: env
            - name: FIREBASE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  key: FIREBASE_PROJECT_ID
                  name: env
            - name: FIREBASE_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: FIREBASE_STORAGE_BUCKET
                  name: env
            - name: GITHUB_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  key: GITHUB_CALLBACK_URL
                  name: env
            - name: GITHUB_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: GITHUB_CLIENT_ID
                  name: env
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: GITHUB_CLIENT_SECRET
                  name: env
            - name: GOOGLE_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_API_KEY
                  name: env
            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_CALLBACK_URL
                  name: env
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: env
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: env
            - name: GOOGLE_CSE_ID
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_CSE_ID
                  name: env
            - name: GOOGLE_KEY
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_KEY
                  name: env
            - name: HELP_AND_FAQ_URL
              valueFrom:
                configMapKeyRef:
                  key: HELP_AND_FAQ_URL
                  name: env
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  key: HOST
                  name: env
            - name: ILLEGAL_MODEL_REQ_SCORE
              valueFrom:
                configMapKeyRef:
                  key: ILLEGAL_MODEL_REQ_SCORE
                  name: env
            - name: JWT_REFRESH_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_REFRESH_SECRET
                  name: env
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: env
            - name: LIMIT_CONCURRENT_MESSAGES
              valueFrom:
                configMapKeyRef:
                  key: LIMIT_CONCURRENT_MESSAGES
                  name: env
            - name: LIMIT_MESSAGE_IP
              valueFrom:
                configMapKeyRef:
                  key: LIMIT_MESSAGE_IP
                  name: env
            - name: LIMIT_MESSAGE_USER
              valueFrom:
                configMapKeyRef:
                  key: LIMIT_MESSAGE_USER
                  name: env
            - name: LOGIN_MAX
              valueFrom:
                configMapKeyRef:
                  key: LOGIN_MAX
                  name: env
            - name: LOGIN_VIOLATION_SCORE
              valueFrom:
                configMapKeyRef:
                  key: LOGIN_VIOLATION_SCORE
                  name: env
            - name: LOGIN_WINDOW
              valueFrom:
                configMapKeyRef:
                  key: LOGIN_WINDOW
                  name: env
            - name: MEILI_HOST
              valueFrom:
                configMapKeyRef:
                  key: MEILI_HOST
                  name: env
            - name: MEILI_MASTER_KEY
              valueFrom:
                configMapKeyRef:
                  key: MEILI_MASTER_KEY
                  name: env
            - name: MEILI_NO_ANALYTICS
              valueFrom:
                configMapKeyRef:
                  key: MEILI_NO_ANALYTICS
                  name: env
            - name: MESSAGE_IP_MAX
              valueFrom:
                configMapKeyRef:
                  key: MESSAGE_IP_MAX
                  name: env
            - name: MESSAGE_IP_WINDOW
              valueFrom:
                configMapKeyRef:
                  key: MESSAGE_IP_WINDOW
                  name: env
            - name: MESSAGE_USER_MAX
              valueFrom:
                configMapKeyRef:
                  key: MESSAGE_USER_MAX
                  name: env
            - name: MESSAGE_USER_WINDOW
              valueFrom:
                configMapKeyRef:
                  key: MESSAGE_USER_WINDOW
                  name: env
            - name: MESSAGE_VIOLATION_SCORE
              valueFrom:
                configMapKeyRef:
                  key: MESSAGE_VIOLATION_SCORE
                  name: env
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGO_URI
                  name: env
            - name: NON_BROWSER_VIOLATION_SCORE
              valueFrom:
                configMapKeyRef:
                  key: NON_BROWSER_VIOLATION_SCORE
                  name: env
            - name: NO_INDEX
              valueFrom:
                configMapKeyRef:
                  key: NO_INDEX
                  name: env
            - name: OPENAI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_API_KEY
                  name: env
            - name: OPENAI_MODERATION
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_MODERATION
                  name: env
            - name: OPENAI_MODERATION_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: OPENAI_MODERATION_API_KEY
                  name: env
            - name: OPENID_BUTTON_LABEL
              valueFrom:
                configMapKeyRef:
                  key: OPENID_BUTTON_LABEL
                  name: env
            - name: OPENID_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  key: OPENID_CALLBACK_URL
                  name: env
            - name: OPENID_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: OPENID_CLIENT_ID
                  name: env
            - name: OPENID_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: OPENID_CLIENT_SECRET
                  name: env
            - name: OPENID_IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  key: OPENID_IMAGE_URL
                  name: env
            - name: OPENID_ISSUER
              valueFrom:
                configMapKeyRef:
                  key: OPENID_ISSUER
                  name: env
            - name: OPENID_REQUIRED_ROLE
              valueFrom:
                configMapKeyRef:
                  key: OPENID_REQUIRED_ROLE
                  name: env
            - name: OPENID_REQUIRED_ROLE_PARAMETER_PATH
              valueFrom:
                configMapKeyRef:
                  key: OPENID_REQUIRED_ROLE_PARAMETER_PATH
                  name: env
            - name: OPENID_REQUIRED_ROLE_TOKEN_KIND
              valueFrom:
                configMapKeyRef:
                  key: OPENID_REQUIRED_ROLE_TOKEN_KIND
                  name: env
            - name: OPENID_SCOPE
              valueFrom:
                configMapKeyRef:
                  key: OPENID_SCOPE
                  name: env
            - name: OPENID_SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  key: OPENID_SESSION_SECRET
                  name: env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: env
            - name: PROXY
              valueFrom:
                configMapKeyRef:
                  key: PROXY
                  name: env
            - name: REFRESH_TOKEN_EXPIRY
              valueFrom:
                configMapKeyRef:
                  key: REFRESH_TOKEN_EXPIRY
                  name: env
            - name: REGISTER_MAX
              valueFrom:
                configMapKeyRef:
                  key: REGISTER_MAX
                  name: env
            - name: REGISTER_WINDOW
              valueFrom:
                configMapKeyRef:
                  key: REGISTER_WINDOW
                  name: env
            - name: REGISTRATION_VIOLATION_SCORE
              valueFrom:
                configMapKeyRef:
                  key: REGISTRATION_VIOLATION_SCORE
                  name: env
            - name: SD_WEBUI_URL
              valueFrom:
                configMapKeyRef:
                  key: SD_WEBUI_URL
                  name: env
            - name: SEARCH
              valueFrom:
                configMapKeyRef:
                  key: SEARCH
                  name: env
            - name: SERPAPI_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: SERPAPI_API_KEY
                  name: env
            - name: SESSION_EXPIRY
              valueFrom:
                configMapKeyRef:
                  key: SESSION_EXPIRY
                  name: env
            - name: TAVILY_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: TAVILY_API_KEY
                  name: env
            - name: TRAVERSAAL_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: TRAVERSAAL_API_KEY
                  name: env
            - name: WOLFRAM_APP_ID
              valueFrom:
                configMapKeyRef:
                  key: WOLFRAM_APP_ID
                  name: env
            - name: ZAPIER_NLA_API_KEY
              valueFrom:
                configMapKeyRef:
                  key: ZAPIER_NLA_API_KEY
                  name: env
          image: getmeili/meilisearch:v1.7.3
          name: chat-meilisearch
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch-claim0
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "100Mi"
      restartPolicy: Always
      volumes:
        - name: meilisearch-claim0
          persistentVolumeClaim:
            claimName: meilisearch-claim0
