apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: meilisearch
  name: meilisearch
spec:
  replicas: {{ .Values.containers.meili.replicas }}
  selector:
    matchLabels:
      io.kompose.service: meilisearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: meilisearch
    spec:
      containers:
        - name: {{ .Values.containers.meili.name }}
          image: {{ .Values.containers.meili.registry }}/{{ .Values.containers.meili.image }}:{{ .Values.containers.meili.version }}
          envFrom:
            - configMapRef:
                name: env
          env:
            - name: MEILI_HOST
              valueFrom:
                configMapKeyRef:
                  key: MEILI_HOST
                  name: env
            - name: MEILI_MASTER_KEY
              valueFrom:
                configMapKeyRef:
                  key: MEILI_MASTER_KEY
                  name: env
            - name: MEILI_NO_ANALYTICS
              valueFrom:
                configMapKeyRef:
                  key: MEILI_NO_ANALYTICS
                  name: env
          volumeMounts:
            - mountPath: /meili_data
              name: meilisearch-claim0
          resources:
            limits:
              cpu: {{ .Values.containers.meili.resources.limits.cpu }}
              memory: {{ .Values.containers.meili.resources.limits.memory }}
            requests:
              cpu: {{ .Values.containers.meili.resources.requests.cpu }}
              memory: {{ .Values.containers.meili.resources.requests.memory }}
      restartPolicy: Always
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: meilisearch-claim0
          persistentVolumeClaim:
            claimName: meilisearch-claim0
