apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: mongodb
        app: mongodb
    spec:
      containers:
        - args:
            - mongod
            - --noauth
          image: mongo
          name: chat-mongodb
          envFrom:
            - configMapRef:
                name: env
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-claim0
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "100Mi"
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: mongodb-claim0
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
