apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: rag
    app: rag
  name: {{ .Values.containers.rag.name }}
spec:
  replicas: {{ .Values.containers.rag.replicas }}
  selector:
    matchLabels:
      io.kompose.service: rag
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: rag
    spec:
      containers:
        - name: {{ .Values.containers.rag.name }}
          image: "{{ .Values.containers.rag.registry }}/{{ .Values.containers.rag.image }}:{{ .Values.containers.rag.version }}"
          env:
            - name: RAG_PORT
              value: "8000"
          envFrom:
            - configMapRef:
                name: env
          resources:
            limits:
              cpu: {{ .Values.containers.rag.resources.limits.cpu }}
              memory: {{ .Values.containers.rag.resources.limits.memory }}
            requests:
              cpu: {{ .Values.containers.rag.resources.requests.cpu }}
              memory: {{ .Values.containers.rag.resources.requests.memory }}
      restartPolicy: Always
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
