apiVersion: v1
kind: Service
metadata:
  name: rag
  labels:
    io.kompose.service: rag
spec:
  selector:
    io.kompose.service: rag
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000