apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: db
  name: vectordb
spec:
  replicas: {{ .Values.containers.vectordb.replicas }}
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/compose-default: "true"
        io.kompose.service: db
    spec:
      containers:
        - name: {{ .Values.containers.vectordb.name }}
          image: "{{ .Values.containers.vectordb.registry }}/{{ .Values.containers.vectordb.image }}:{{ .Values.containers.vectordb.version }}"
          envFrom:
            - configMapRef:
                name: my-configmap
          env:
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_USER
              value: myuser
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata2
          resources:
            limits:
              cpu: {{ .Values.containers.vectordb.resources.limits.cpu }}
              memory: {{ .Values.containers.vectordb.resources.limits.memory }}
            requests:
              cpu: {{ .Values.containers.vectordb.resources.requests.cpu }}
              memory: {{ .Values.containers.vectordb.resources.requests.memory }}
      restartPolicy: Always
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: pgdata2
          persistentVolumeClaim:
            claimName: pgdata2
