apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        io.kompose.service: db
spec:
    type: ClusterIP
    ports:
        - port: 5432
          targetPort: 5432
    selector:
        io.kompose.service: db